package com.banking.util;

import com.banking.model.TransferReceipt;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.*;
import java.awt.Color;
import java.io.*;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/** Read-only, one-page proof using the existing PDFBox dependency. */
public final class TransferReceiptPdf {
    private static final Color WINE=new Color(81,17,39), GOLD=new Color(228,185,104), INK=new Color(43,35,38);
    private TransferReceiptPdf(){}
    public static byte[] create(TransferReceipt receipt)throws IOException {
        try(PDDocument document=new PDDocument();ByteArrayOutputStream out=new ByteArrayOutputStream()) {
            PDPage page=new PDPage(PDRectangle.A4);document.addPage(page);
            PDFont regular=new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            PDFont bold=new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            document.getDocumentInformation().setTitle("LankaTrust Money Transfer Receipt - "+receipt.reference());
            document.getDocumentInformation().setAuthor("LankaTrust Banking System");
            try(PDPageContentStream stream=new PDPageContentStream(document,page)) {
                stream.setNonStrokingColor(new Color(255,253,249));stream.addRect(0,0,page.getMediaBox().getWidth(),page.getMediaBox().getHeight());stream.fill();
                text(stream,"LankaTrust",48,778,bold,28,WINE);
                text(stream,"Trust in every transaction.",49,756,regular,10,INK);
                line(stream,738,GOLD,2);
                text(stream,"MONEY TRANSFER RECEIPT",48,704,bold,17,WINE);
                stream.setNonStrokingColor(new Color(231,241,233));stream.addRect(48,652,499,30);stream.fill();
                text(stream,"TRANSFER SUCCESSFUL",62,663,bold,11,new Color(37,99,64));
                text(stream,"AMOUNT TRANSFERRED",48,624,regular,9,INK);
                text(stream,"LKR "+String.format(Locale.ROOT,"%,.2f",receipt.amount()),48,582,bold,32,WINE);
                line(stream,560,GOLD,.7f);
                field(stream,"Transaction Reference",receipt.reference(),528,regular,bold);
                // Omit unavailable timestamps rather than inventing a completion date.
                if(receipt.timestamp()!=null)field(stream,"Date & Time",receipt.timestamp().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),464,regular,bold);
                field(stream,"From Account",TransferReceipt.mask(receipt.senderAccount()),400,regular,bold);
                if(receipt.receiverAccount()!=null&&!receipt.receiverAccount().isBlank())
                    field(stream,"To Account",TransferReceipt.mask(receipt.receiverAccount()),336,regular,bold);
                field(stream,"Transaction Type",receipt.type(),272,regular,bold);
                field(stream,"Status",receipt.status(),208,regular,bold);
                line(stream,143,GOLD,.7f);
                text(stream,"This receipt was automatically generated by",48,117,regular,10,INK);
                text(stream,"LankaTrust Banking System.",48,101,bold,10,WINE);
            }
            document.save(out);return out.toByteArray();
        }
    }
    private static void field(PDPageContentStream stream,String label,String value,float y,PDFont regular,PDFont bold)throws IOException {
        text(stream,label,48,y,regular,10,INK);
        // Long stored references wrap without changing their content.
        StringBuilder line=new StringBuilder();float baseline=y-21;
        for(char ch:value.toCharArray()) {
            if(bold.getStringWidth(line.toString()+ch)/1000*12>497){text(stream,line.toString(),48,baseline,bold,12,WINE);line.setLength(0);baseline-=15;}
            line.append(ch);
        }
        text(stream,line.toString(),48,baseline,bold,12,WINE);
    }
    private static void text(PDPageContentStream stream,String text,float x,float y,PDFont font,float size,Color color)throws IOException {
        stream.setNonStrokingColor(color);stream.beginText();stream.setFont(font,size);stream.newLineAtOffset(x,y);stream.showText(text);stream.endText();
    }
    private static void line(PDPageContentStream stream,float y,Color color,float width)throws IOException {
        stream.setStrokingColor(color);stream.setLineWidth(width);stream.moveTo(48,y);stream.lineTo(547,y);stream.stroke();
    }
}
