<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html><html lang="en"><head>
<script src="<%= request.getContextPath() %>/assets/js/theme-init.js"></script><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LankaTrust | Trust in every transaction.</title><meta name="description" content="A thoughtful approach to personal banking with LankaTrust."><link rel="stylesheet" href="<%= request.getContextPath() %>/assets/css/public.css"><script defer src="<%= request.getContextPath() %>/assets/js/public.js"></script><link rel="stylesheet" href="<%= request.getContextPath() %>/assets/css/banking-system.css">
<script defer src="<%= request.getContextPath() %>/assets/js/banking-ui.js"></script>
<link rel="stylesheet" href="<%= request.getContextPath() %>/assets/css/design-system.css">
<link rel="stylesheet" href="<%= request.getContextPath() %>/assets/css/workspaces.css">
<script defer src="<%= request.getContextPath() %>/assets/js/workspaces.js"></script>
</head><body class="public-site">
<a class="skip" href="#main">Skip to content</a><div class="utility"><div class="wrap">Personal banking <span>A considered approach to your finances.</span></div></div>
<header><nav class="wrap nav" aria-label="Main navigation"><a class="wordmark" href="<%= request.getContextPath() %>/"><span class="monogram">LT</span>LankaTrust</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="nav-links">Menu ☰</button><div id="nav-links" class="nav-links"><a href="#home">Home</a><a href="#personal">Personal Banking</a><a href="#accounts">Accounts</a><a href="#cards">Cards</a><a href="#loans">Loans</a><a href="#investments">Investments</a><a href="#about">About Us</a><a href="#contact">Contact</a><a href="<%= request.getContextPath() %>/login.jsp">Login</a><a class="button small" href="<%= request.getContextPath() %>/register.jsp">Open an Account</a></div></nav></header>
<main id="main"><section id="home" class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">YOUR LIFE. YOUR AMBITIONS.</p><h1>Trust in every<br><em>transaction.</em></h1><p>For the everyday essentials and the plans that matter. Discover a thoughtful way to bank with LankaTrust.</p><div class="actions"><a class="button" href="<%= request.getContextPath() %>/login.jsp">Login to Banking ↗</a><a class="text-link" href="<%= request.getContextPath() %>/register.jsp">Open an Account →</a></div><p class="signature">Trust in every transaction.</p></div><figure class="banking-art" aria-label="LankaTrust illustrative banking card"><div class="art-card"><span class="art-brand">LankaTrust</span><span class="art-chip" aria-hidden="true"></span><strong>Your everyday.<br>Your next chapter.</strong><small>PERSONAL BANKING / DEMONSTRATION</small></div><figcaption>A clearer view of your financial world.</figcaption></figure></div></section>
<section id="personal" class="section wrap"><div class="heading"><div><p class="eyebrow">PERSONAL BANKING</p><h2>Built around your everyday.</h2></div><p>One place to manage your money, keep track of payments and take the next step with confidence.</p></div><div class="service-row"><a href="#accounts"><span>01 / SAVE</span><h3>Save &amp; manage</h3><p>Your accounts, clearly in view. →</p></a><a href="#cards"><span>02 / SPEND</span><h3>Stay in control</h3><p>Card services at your fingertips. →</p></a><a href="#loans"><span>03 / PLAN</span><h3>Move forward</h3><p>Explore your next possibility. →</p></a></div></section>
<section id="accounts" class="section neutral"><div class="wrap split"><div><p class="eyebrow">ACCOUNTS</p><h2>A good place<br>to begin.</h2><p>Bring your everyday banking together. View savings and current accounts, review your balances and follow each transaction from your personal dashboard.</p><ul><li>Savings and current account services</li><li>Clear balances and transaction history</li><li>Account requests you can follow online</li></ul><a class="button" href="<%= request.getContextPath() %>/register.jsp">Open an Account →</a></div><div class="editorial"><span class="large-mark">LT</span><p class="eyebrow">LANKATRUST PERSONAL BANKING</p><h3>Small steps.<br>Meaningful progress.</h3><p>From your first account to your next financial milestone, start with a clear view of where you stand.</p><a class="text-link" href="<%= request.getContextPath() %>/customer/accounts">View your accounts →</a></div></div></section>
<section id="cards" class="section wrap split"><div class="card-visual" aria-label="Illustrative LankaTrust demonstration card"><span>LankaTrust</span><div class="chip" aria-hidden="true"></div><strong>Everyday, in your hands.</strong><small>DEMONSTRATION CARD · NO PAYMENT NETWORK</small></div><div><p class="eyebrow">CARD SERVICES</p><h2>More control.<br>Less complication.</h2><p>Request a debit or credit card, track its approval and manage your settings. Review limits and block a card through your banking portal.</p><a class="text-link" href="<%= request.getContextPath() %>/customer/cards">Explore card services →</a><p class="fine">Card issuance in this platform is for demonstration purposes.</p></div></section>
<section id="loans" class="section neutral"><div class="wrap split"><div><p class="eyebrow">LOANS</p><h2>For plans worth<br>moving towards.</h2><p>A fresh beginning. A personal milestone. Apply online, follow the review process and see your approved terms before accepting a loan.</p><ul><li>Application progress in one place</li><li>Terms available before acceptance</li><li>Installment and repayment tracking</li></ul><a class="button" href="<%= request.getContextPath() %>/customer/loans">View loan options →</a></div><img class="section-image" src="<%= request.getContextPath() %>/assets/images/home.jpg" width="1200" height="800" loading="lazy" alt="Modern home with a pool and outdoor living space"></div></section>
<section id="investments" class="section wrap split"><img class="section-image" src="<%= request.getContextPath() %>/assets/images/city.jpg" width="1600" height="1067" loading="lazy" alt="Modern office buildings viewed from below"><div><p class="eyebrow">INVESTMENTS</p><h2>Give tomorrow<br>some thought today.</h2><p>Explore investment services, review your application terms and keep track of active holdings, maturity dates and withdrawals.</p><a class="text-link" href="<%= request.getContextPath() %>/customer/investments">Explore investments →</a><p class="fine">Rates and calculations use configurable demonstration terms. Review the terms shown in your portal.</p></div></section>
<section id="digital" class="section navy"><div class="wrap"><div class="heading"><div><p class="eyebrow">DIGITAL BANKING</p><h2>Your banking.<br>Within easy reach.</h2></div><a class="button gold" href="<%= request.getContextPath() %>/login.jsp">Access your banking →</a></div><div class="feature-grid"><div><span>01 / TRANSFER</span><h3>Move money simply</h3><p>Transfer between active LankaTrust accounts and review the result in your history.</p></div><div><span>02 / PAY</span><h3>Keep payments organised</h3><p>Record bill payments and prepare scheduled payments to execute when due.</p></div><div><span>03 / MANAGE</span><h3>Stay informed</h3><p>Review requests, manage your profile and contact customer service.</p></div></div></div></section>
<section id="why" class="section wrap"><div class="heading"><div><p class="eyebrow">WHY LANKATRUST</p><h2>Clarity comes first.</h2></div><p>A banking experience focused on useful details, straightforward actions and a clear view of your money.</p></div><div class="feature-grid"><div><h3>Everything in perspective</h3><p>Balances, transactions and service requests, brought together in your personal portal.</p></div><div><h3>You stay involved</h3><p>Follow applications and review approved loan terms before accepting.</p></div><div><h3>A clear path to support</h3><p>Send a request, read the response and track the conversation in one place.</p></div></div></section>
<section id="security" class="section neutral"><div class="wrap split"><div><p class="eyebrow">SECURITY &amp; TRUST</p><h2>Care at every step.</h2><p>Protection is part of how LankaTrust works, from signing in to completing an account operation.</p><p class="security-tip">Keep your password private. Sign out when you finish, especially on a shared device.</p></div><div class="security-rows"><div><h3>Protected sign-in</h3><p>Password hashing and session checks support account access.</p></div><div><h3>Access with purpose</h3><p>Customer ownership checks and staff role permissions protect banking operations.</p></div><div><h3>Consistent transactions</h3><p>Financial changes commit together or roll back on failure.</p></div></div></div></section>
<section id="about" class="section wrap split"><div><p class="eyebrow">ABOUT LANKATRUST</p><h2>A local perspective.<br>A considered experience.</h2></div><div><p class="lead">Created with Sri Lankan banking needs in mind, LankaTrust brings everyday financial services into a connected digital experience.</p><p>LankaTrust is a university web-based banking project demonstrating customer services and banking operations. It is not a licensed commercial bank and does not provide real-world banking services.</p></div></section>
<section id="achievements" class="section neutral"><div class="wrap"><p class="eyebrow">PLATFORM ACHIEVEMENTS</p><h2>Thoughtfully built, from the inside out.</h2><div class="achievement-grid"><div><span>01</span><h3>Secure Banking Architecture</h3></div><div><span>02</span><h3>Modern Digital Banking Experience</h3></div><div><span>03</span><h3>Customer-Centred Design</h3></div><div><span>04</span><h3>Role-Based Banking Operations</h3></div></div><p class="fine">Project capabilities and design milestones. These are not external awards or certifications.</p></div></section>
<section id="contact" class="section wrap split"><div><p class="eyebrow">CUSTOMER SUPPORT</p><h2>Let’s take the<br>next step together.</h2><p>Sign in to send a service request or open a support ticket. Your messages and responses stay together in your portal.</p><a class="button" href="<%= request.getContextPath() %>/customer/requests">Contact customer service →</a></div><div class="contact-options"><h3>How can we help?</h3><details><summary>How do I get started?</summary><p>Select Open an Account, complete registration, then sign in to your customer portal.</p></details><details><summary>Where can I follow an application?</summary><p>Your Cards, Loans and Investments pages show the status of your requests.</p></details><details><summary>How do scheduled payments work?</summary><p>Create a payment with a future date. Return to Payments on or after that date to execute it. Payments do not run automatically.</p></details></div></section></main>
<footer><div class="wrap footer-grid"><div><a class="wordmark" href="#home"><span class="monogram">LT</span>LankaTrust</a><p>Trust in every transaction.</p></div><div><h3>Personal banking</h3><a href="#accounts">Accounts</a><a href="#cards">Cards</a><a href="#loans">Loans</a><a href="#investments">Investments</a></div><div><h3>Here to help</h3><a href="#security">Security &amp; trust</a><a href="#contact">Customer support</a><a href="#about">About LankaTrust</a></div><div><h3>Your banking</h3><a href="<%= request.getContextPath() %>/login.jsp">Login</a><a href="<%= request.getContextPath() %>/register.jsp">Open an Account</a></div></div><div class="wrap footer-bottom"><span>&copy; <%= java.time.Year.now() %> LankaTrust. University banking project.</span><span>Demonstration platform · No real-world settlement</span></div></footer></body></html>
