import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
const base=process.argv[2],profile=path.resolve('target/notification-browser-profile');
fs.mkdirSync(profile,{recursive:true});
const chrome=process.env.NOTIFICATION_CHROME_PORT?null:spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore',windowsHide:true});
let ws;let checks=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function check(ok,label){if(!ok)throw new Error(label);console.log('BROWSER PASS '+label);checks++;}
try {
 const portFile=path.join(profile,'DevToolsActivePort');
 if(chrome)for(let n=0;n<100&&!fs.existsSync(portFile);n++)await sleep(100);
 const port=process.env.NOTIFICATION_CHROME_PORT||fs.readFileSync(portFile,'utf8').split('\n')[0];
 const pages=await(await fetch(`http://127.0.0.1:${port}/json`)).json();
 ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let serial=0;const pending=new Map();
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}});
 const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++serial,{resolve,reject});ws.send(JSON.stringify({id:serial,method,params}));});
 const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
 const nav=async route=>{await call('Page.navigate',{url:base+route});await sleep(300);for(let n=0;n<100;n++){try{if(await ev('document.readyState==="complete"'))return;}catch{}await sleep(100);}throw new Error('navigation timed out');};
 const identity=async(id,role,route)=>{await nav(`/fixture?id=${id}&role=${role}`);await nav(route);};
 const submit=async expression=>{await ev(expression);await sleep(400);for(let i=0;i<100;i++){try{if(await ev('document.readyState==="complete"'))return;}catch{}await sleep(100);}};
 await identity(1,'CUSTOMER','/customer/tickets');
 await submit(`(()=>{const f=document.querySelector('input[value="ticket"]').form;f.subject.value='Browser ATM Withdrawal Issue';f.description.value='ATM withdrawal failed but money was deducted.';f.requestSubmit();})()`);
 const id=await ev(`(()=>{const a=[...document.querySelectorAll('.support-ticket')].find(a=>a.textContent.includes('Browser ATM Withdrawal Issue'));return a.id.replace('ticket-','');})()`);
 check(!!id,'customer creates ATM ticket using UI');
 await identity(1,'CUSTOMER_SERVICE_OFFICER','/service/dashboard.jsp');
 await submit(`(()=>{const f=document.querySelector('#support-ticket-${id} .ticket-assign');f.assignedRole.value='CARD_SERVICES_OFFICER';f.requestSubmit();})()`);
 await identity(3,'CARD_SERVICES_OFFICER','/card/dashboard.jsp');
 check(await ev('!!document.querySelector(".notify-badge")'),'card bell shows unread badge');
 await ev('document.querySelector(".notify-bell").click()');
 check(await ev('document.querySelector(".notification-center").open'),'bell click opens dropdown');
 check(await ev(`document.querySelector('.notify-popup').textContent.includes('New Assigned Support Ticket')`),'assignment notification visible in open dropdown');
 await submit(`document.querySelector('.notify-popup form.notify-item').requestSubmit()`);
 check(await ev(`location.hash==='#support-ticket-${id}'&&document.querySelector('#support-ticket-${id} details').open`),'notification click opens and focuses staff ticket');
 await submit(`(()=>{const f=document.querySelector('#support-ticket-${id} input[value="ticket-status"]').form;f.status.value='IN_PROGRESS';f.requestSubmit();})()`);
 await submit(`(()=>{const f=document.querySelector('#support-ticket-${id} .ticket-reply');f.reason.value='Card Services is investigating your ATM transaction.';f.requestSubmit();})()`);
 await identity(1,'CUSTOMER','/customer/dashboard');
 const count=await ev('Number(document.querySelector(".notify-badge").textContent)');
 await ev('document.querySelector(".notify-bell").click()');
 check(await ev(`document.querySelector('.notify-popup').textContent.includes('New Support Reply')&&document.querySelector('.notify-popup').textContent.includes('Ticket Status Updated')`),'customer popup shows reply and status updates');
 await sleep(250);fs.writeFileSync('verification/notification-desktop.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await ev('document.querySelector("h1").click()');check(await ev('!document.querySelector(".notification-center").open'),'outside click closes dropdown');
 await ev('document.querySelector(".notify-bell").focus()');await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await call('Input.dispatchKeyEvent',{type:'char',text:'\r',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
 check(await ev('document.querySelector(".notification-center").open'),'keyboard Enter opens bell');
 await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
 check(await ev('!document.querySelector(".notification-center").open&&document.activeElement.matches(".notify-bell")'),'Escape closes popup and restores focus');
 await ev('document.querySelector(".notify-bell").click()');
 await submit(`document.querySelector('.notify-popup form.notify-item').requestSubmit()`);
 check(await ev(`location.hash==='#ticket-${id}'&&document.body.textContent.includes('Card Services is investigating your ATM transaction.')`),'customer notification opens relevant conversation');
 check(await ev('Number(document.querySelector(".notify-badge").textContent)')===count-1,'click reduces unread count');
 await ev('document.querySelector(".notify-bell").click()');await submit(`document.querySelector('.notify-heading form').requestSubmit()`);
 check(await ev('!document.querySelector(".notify-badge")'),'mark all removes unread badge');
 await identity(3,'CARD_SERVICES_OFFICER',`/card/dashboard.jsp?ticket=${id}`);
 await submit(`(()=>{const f=document.querySelector('#support-ticket-${id} input[value="ticket-status"]').form;f.status.value='RESOLVED';f.requestSubmit();})()`);
 await identity(1,'CUSTOMER','/customer/dashboard');await ev('document.querySelector(".notify-bell").click()');
 check(await ev(`document.querySelector('.notify-popup').textContent.includes('Ticket Resolved')`),'resolution notification appears on customer reload');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 check(await ev(`(()=>{const r=document.querySelector('.notify-popup').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})()`),'mobile popup fits viewport');
 await sleep(250);fs.writeFileSync('verification/notification-mobile.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 console.log(`ALL ${checks} BROWSER CHECKS PASSED`);
} finally {if(ws)ws.close();chrome?.kill();}
