import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
const base=process.argv[2];
const original=spawnSync('node',['target/task3-tools/notification-browser.mjs',base],{stdio:'inherit',windowsHide:true,timeout:100000});
if(original.status!==0)throw new Error('Existing notification browser interactions failed');
const port=process.env.NOTIFICATION_CHROME_PORT||'9237';
const targets=await(await fetch(`http://127.0.0.1:${port}/json`)).json();
const ws=new WebSocket(targets.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let serial=0,checks=0,current='';const pending=new Map(),failures=[],errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push({page:current,error:m.params.exceptionDetails});else if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')errors.push({page:current,error:m.params.args});});
const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++serial,{resolve,reject});ws.send(JSON.stringify({id:serial,method,params}));});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ev=async expression=>{const result=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
const check=(ok,label,detail)=>{checks++;if(!ok){failures.push({label,detail,page:current});console.log('UX FAIL '+label+' '+JSON.stringify(detail));}};
const ready=async()=>{await sleep(180);for(let i=0;i<100;i++){try{if(await ev('document.readyState==="complete"'))return;}catch{}await sleep(80);}throw new Error('Load timeout');};
const nav=async route=>{current=route;await call('Page.navigate',{url:base+route});await ready();};
const identity=async(id,role)=>nav(`/fixture?id=${id}&role=${role}`);
const size=width=>call('Emulation.setDeviceMetricsOverride',{width,height:width===390?844:900,deviceScaleFactor:1,mobile:false});
const shot=async name=>{await sleep(360);fs.writeFileSync('verification/ux-'+name+'.png',Buffer.from((await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));};
const key=async(key,code=key,vk,modifiers=0)=>{await call('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:vk,modifiers});await call('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:vk,modifiers});await sleep(80);};
const click=async selector=>{const box=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)return null;const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:r.width,h:r.height};})()`);if(!box||!box.w||!box.h)throw new Error('Not visible: '+selector);await call('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x,y:box.y,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x,y:box.y,button:'left',clickCount:1});await sleep(120);};
try {
 await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});
 if(process.env.UX_CARD_ONLY!=='1'){
 const roles=['CUSTOMER_SERVICE_OFFICER','LOAN_OFFICER','CARD_SERVICES_OFFICER','INVESTMENT_OFFICER','COMPLIANCE_RISK_OFFICER','SYSTEM_ADMIN'];
 const pages=[['PUBLIC',0,'/'],['PUBLIC',0,'/login.jsp'],['PUBLIC',0,'/register.jsp'],...['dashboard','accounts','transactions','transfer','payments','cards','loans','investments','requests','tickets','settings','products','notifications'].map(s=>['CUSTOMER',1,'/customer/'+s]),...roles.map((r,i)=>[r,i+1,'/employee/dashboard']),['SYSTEM_ADMIN',6,'/employee/notifications']];
 for(const theme of ['light','dark'])for(const width of [1440,1024,768,390]){
  await size(width);let lastRole='';
  for(const [role,id,route] of pages){
   if(role!==lastRole){if(role==='PUBLIC')await call('Network.clearBrowserCookies');else await identity(id,role);lastRole=role;}
   await ev(`localStorage.setItem('lankatrust-theme','${theme}')`);await nav(route);
   const result=await ev(`({title:document.title,error:/HTTP Status 500|JasperException|Unable to load|temporarily unavailable/.test(document.body.innerText),shell:document.body.classList.contains('workspace-app'),overflow:document.documentElement.scrollWidth>innerWidth+2,active:[...document.querySelectorAll('.bank-workspace')].filter(e=>!e.hidden).map(e=>e.dataset.workspace),wide:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&!e.closest('.workspace-table-region,.ui-table-scroll')).slice(0,4).map(e=>e.className)})`);
   check(!result.error&&(role==='PUBLIC'||result.shell),`${theme} ${width} ${role} ${route}: render`,result);
   check(!result.overflow,`${theme} ${width} ${role} ${route}: viewport`,result);
   if(role!=='CUSTOMER'&&role!=='PUBLIC'&&route==='/employee/dashboard')check(result.active.length===1&&result.active[0]==='workspace-home','staff starts on one control-center workspace',result);
   if(route==='/customer/dashboard'){
    const quick=await ev(`([...document.querySelectorAll('.control-actions .quick-action-tile')].map(e=>{const r=e.getBoundingClientRect();return {name:e.innerText,y:r.y,bottom:r.bottom,visible:r.y>=0&&r.bottom<=innerHeight};}))`);
    check(quick.length===6&&quick.every(a=>a.visible),'all six customer actions visible without scrolling',quick);
   }
   if([1440,390].includes(width)&&['/','/login.jsp','/customer/dashboard','/customer/tickets'].includes(route))await shot(`${theme}-${width}-${route.replaceAll('/','-')||'home'}`);
   if(width===1440&&role==='SYSTEM_ADMIN'&&route==='/employee/dashboard')await shot(theme+'-admin-dashboard');
   if(width===1440&&role==='CUSTOMER_SERVICE_OFFICER')await shot(theme+'-service-dashboard');
   if(route==='/customer/tickets'&&width===390&&await ev('!!document.querySelector(".ticket-selector")')){
    await click('.ticket-selector');check(await ev('document.querySelector(".ticket-workbench").classList.contains("show-ticket")&&[...document.querySelectorAll(".support-ticket")].filter(t=>!t.hidden).length===1'),'mobile ticket selection opens one detail view');await shot(theme+'-mobile-ticket');await click('.ticket-back');check(await ev('!document.querySelector(".ticket-workbench").classList.contains("show-ticket")'),'mobile returns to ticket list');
   }
  }
 }
 // Required customer acceptance: actual pointer clicks, never scroll-to-element.
 for(const width of [1440,1024,768,390]){
  await size(width);await identity(1,'CUSTOMER');
  for(const path of ['transfer#action-transfer','payments#action-pay','loans#action-apply','cards','investments#action-apply','tickets#action-ticket']){
   await nav('/customer/dashboard');await click(`.control-actions a[href$="/customer/${path}"]`);await ready();
   check(await ev(`location.pathname==='/customer/${path.split('#')[0]}'`),`${width} quick action reaches ${path}`);
   if(path.includes('#'))check(await ev('document.querySelector(".action-dialog").open&&!!document.querySelector(".action-dialog form")'),`${width} quick action opens original form ${path}`);
   if(path==='payments#action-pay'&&[1440,390].includes(width))await shot(width+'-customer-quick-action-modal');
   if(path.includes('#')){await key('Escape','Escape',27);check(await ev('!document.querySelector(".action-dialog").open'),`${width} modal Escape closes`);}
  }
 }
 await size(1440);await identity(6,'SYSTEM_ADMIN');await nav('/employee/dashboard');
 for(const width of [1024,768,390]){
  await size(width);for(const id of ['Customers','Employees','Products','Audit-log']){await nav('/employee/dashboard');await click(`.operations-home .quick-action-tile[href="#${id}"]`);check(await ev(`!document.querySelector('[data-workspace="${id}"]').hidden&&scrollY===0`),`${width} admin reaches ${id} without scrolling`);}
 }
 await size(1440);await nav('/employee/dashboard');
 for(const id of ['Customers','Employees','Products','Audit-log']){
  await click(`.operations-sidebar a[href="#${id}"]`);check(await ev(`document.querySelector('[data-workspace="${id}"]').hidden===false&&[...document.querySelectorAll('.bank-workspace')].filter(e=>!e.hidden).length===1&&scrollY===0`),'admin opens only '+id+' without scrolling');await shot('admin-'+id);
 }
 await click('.operations-sidebar a[href="#Employees"]');await click('[data-workspace="Employees"] [data-action-key="action-new-employee"]');check(await ev('document.querySelector(".action-dialog").open&&document.querySelector(".action-dialog input[name=action]").value==="employee-save"'),'admin new employee uses original form');await shot('admin-employee-modal');
 await ev(`(()=>{const f=document.querySelector('.action-dialog form');f.elements.name.value='Workspace Test Employee';f.email.value='workspace-new@example.invalid';f.phone.value='0771234567';f.password.value='Fixture-Login-Only-2026!';f.requestSubmit();})()`);await ready();
 check(await ev('document.querySelector(".ui-toast")&&document.querySelector("[data-workspace=Employees]").hidden===false&&!document.querySelector(".action-dialog").open'),'employee save returns to management workspace with server toast');
 await ev('document.querySelector("[data-workspace=Employees] .collection-toolbar input").value="Workspace Test Employee";document.querySelector("[data-workspace=Employees] .collection-toolbar input").dispatchEvent(new Event("input"))');
 check(await ev('document.querySelectorAll("[data-workspace=Employees] tbody .record-open").length===1'),'employee search narrows loaded authorized records');await click('[data-workspace=Employees] .record-open');check(await ev('document.querySelector(".record-drawer").open'),'employee details open drawer');await shot('admin-employee-drawer');
 await click('.record-drawer details summary');await click('.record-drawer [data-action-key^="action-employee-save-"]');check(await ev('document.querySelector(".action-dialog").open&&document.querySelector(".action-dialog [name=action]").value==="employee-save"'),'edit employee opens original edit form from drawer');
 await ev('document.querySelector(".action-dialog select[name=status]").value="INACTIVE";document.querySelector(".action-dialog form").requestSubmit()');await sleep(100);check(await ev('document.querySelector(".ui-dialog").open'),'employee deactivation asks for confirmation',await ev('[...document.querySelectorAll(".action-dialog input,.action-dialog select")].map(e=>({name:e.name,valid:e.checkValidity(),message:e.validationMessage}))'));await key('Escape','Escape',27);await key('Escape','Escape',27);await key('Escape','Escape',27);
 await click('[data-workspace=Employees] .record-open');await click('.record-drawer [data-action-key^="action-employee-status-"]');await ev('document.querySelector(".action-dialog textarea[name=reason]").value="Test confirmation without saving";document.querySelector(".action-dialog select[name=status]").value="INACTIVE";document.querySelector(".action-dialog form").requestSubmit()');check(await ev('document.querySelector(".ui-dialog").open'),'dedicated employee status action confirms before saving');await shot('admin-status-confirmation');await key('Escape','Escape',27);await key('Escape','Escape',27);await key('Escape','Escape',27);
 for(const [id,role,workspace] of [[1,'CUSTOMER_SERVICE_OFFICER','cash-transactions'],[2,'LOAN_OFFICER','Loans'],[3,'CARD_SERVICES_OFFICER','Cards'],[4,'INVESTMENT_OFFICER','Investments'],[5,'COMPLIANCE_RISK_OFFICER','Audit-log']]){
  await identity(id,role);await nav('/employee/dashboard');await click(`.operations-sidebar a[href="#${workspace}"]`);check(await ev(`[...document.querySelectorAll('.bank-workspace')].filter(e=>!e.hidden).length===1&&scrollY===0`),role+' focused '+workspace);await shot(role+'-workspace');
  await click('.operations-sidebar a[href="#assigned-support-tickets"]');check(await ev('!document.querySelector("[data-workspace=assigned-support-tickets]").hidden'),role+' reaches assigned support immediately');
 }
 await identity(1,'CUSTOMER_SERVICE_OFFICER');await nav('/employee/dashboard');await click('.quick-action-tile[href="#action-cash-deposit"]');check(await ev('document.querySelector(".action-dialog input[name=action]").value==="cash-deposit"'),'cash deposit launches directly from role home');await shot('cash-deposit-modal');await key('Escape','Escape',27);
 for(const width of [1440,1024,768,390]){await size(width);for(const id of ['cash-transactions','Service-requests','assigned-support-tickets']){await nav('/employee/dashboard');await click(`.operations-home .quick-action-tile[href="#${id}"]`);check(await ev(`[...document.querySelectorAll('.bank-workspace')].filter(e=>!e.hidden).length===1&&scrollY===0`),`${width} customer service reaches ${id} without scrolling`);}}
 await size(1440);await identity(1,'CUSTOMER');await nav('/customer/tickets#action-ticket');await ev(`(()=>{const f=document.querySelector('.action-dialog form');f.subject.value='Workspace routing enquiry';f.description.value='Please route this test enquiry.';f.requestSubmit();})()`);await ready();await identity(1,'CUSTOMER_SERVICE_OFFICER');
 await nav('/employee/dashboard#assigned-support-tickets');
 if(await ev('!!document.querySelector(".ticket-selector")')){await click('.ticket-selector');await click('.ticket-detail-pane .support-ticket:not([hidden]) [data-action-key^="action-ticket-assign"]');check(await ev('document.querySelector(".action-dialog").open&&!!document.querySelector(".action-dialog select[name=assignedRole]")'),'assignment modal retains department field');await shot('ticket-assignment-modal');await ev('document.querySelector(".action-dialog select[name=assignedRole]").value="CARD_SERVICES_OFFICER";document.querySelector(".action-dialog form").requestSubmit()');await ready();check(await ev('!document.querySelector(".action-dialog").open&&!!document.querySelector(".ui-toast")'),'assignment saves through original server operation');}
 await identity(3,'CARD_SERVICES_OFFICER');await nav('/employee/dashboard#Cards~PENDING');check(await ev('document.querySelector("#Cards .collection-toolbar select").value==="PENDING"'),'role quick status view applies pending filter');await nav('/employee/dashboard#assigned-support-tickets');await click('.ticket-selector');await click('.ticket-commandbar [data-action-key^="action-ticket-status"]');await ev('document.querySelector(".action-dialog select[name=status]").value="IN_PROGRESS";document.querySelector(".action-dialog form").requestSubmit()');await ready();check(await ev('!!document.querySelector(".ui-toast")&&!document.querySelector(".action-dialog").open'),'ticket status modal submits and closes on success');
 // Browser history resolves the selected workspace, not a long-page anchor scroll.
 await identity(6,'SYSTEM_ADMIN');await nav('/employee/dashboard');await click('.operations-sidebar a[href="#Customers"]');await click('.operations-sidebar a[href="#Products"]');await ev('history.back()');await sleep(200);check(await ev('!document.querySelector("[data-workspace=Customers]").hidden'),'Back restores previous admin workspace');
 await key('k','KeyK',75,2);check(await ev('document.querySelector(".command-dialog").open&&document.activeElement.matches(".command-input")'),'Ctrl K opens action launcher with focus');await ev('document.querySelector(".command-input").value="employee";document.querySelector(".command-input").dispatchEvent(new Event("input"))');check(await ev('document.querySelectorAll(".command-results a").length===2'),'admin command results are role-specific');await shot('command-palette');await key('Escape','Escape',27);
 // Customer support new-ticket modal, focused error return and server success.
 await identity(1,'CUSTOMER');await nav('/customer/tickets#action-ticket');await ev(`(()=>{const f=document.querySelector('.action-dialog form');f.subject.value='Workspace enquiry';f.description.value='Please review this test enquiry.';f.requestSubmit();})()`);await ready();check(await ev('!!document.querySelector(".ui-toast")&&document.body.textContent.includes("Workspace enquiry")&&!document.querySelector(".action-dialog").open'),'new ticket modal submits existing server operation');await shot('support-server-success');
 await click('.ticket-commandbar [data-action-key^="action-ticket-reply"]');await ev('document.querySelector(".action-dialog textarea").value="Additional information from the reply dialog.";document.querySelector(".action-dialog form").requestSubmit()');await ready();check(await ev('document.body.textContent.includes("Additional information from the reply dialog.")'),'reply dialog retains conversation workflow');
 await nav('/customer/requests');check(await ev('document.querySelector("[data-workspace=support-workspace]").hidden&&!document.querySelector("[data-workspace=service-requests]").hidden'),'service requests do not stack unrelated support workspace');
 await nav('/customer/payments#action-pay');await ev(`(()=>{const f=document.querySelector('.action-dialog form');f.recipient.value='CEB';f.billReference.value='UX-TEST';f.amount.value='999999999';f.requestSubmit();})()`);await ready();check(await ev('document.querySelector(".action-dialog").open&&!!document.querySelector(".action-dialog .action-error")'),'server payment error returns to same action dialog');await shot('payment-error-modal');
 await key('Escape','Escape',27);await nav('/customer/dashboard');await click('.notify-bell');await shot('notification-dropdown');await key('Escape','Escape',27);
 await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await nav('/customer/payments#action-pay');check(await ev('getComputedStyle(document.querySelector(".action-dialog")).animationName==="none"'),'reduced motion disables dialog animation');await call('Emulation.setEmulatedMedia',{features:[]});
 }
 // Dedicated card application: actual password login, original form, and temporary database records.
 const cardLogin=async()=>{await call('Network.clearBrowserCookies');await nav('/login.jsp');await ev(`document.querySelector('[name=email]').value='card-applicant@example.invalid';document.querySelector('[name=password]').value='Fixture-Login-Only-2026!';document.querySelector('[name=password]').form.requestSubmit()`);await ready();};
 await cardLogin();check(await ev('location.pathname.endsWith("/customer/dashboard")'),'card applicant uses actual password login');
 for(const theme of ['light','dark'])for(const width of [1440,1024,768,390]){
  await size(width);await nav('/customer/cards');await ev(`document.documentElement.dataset.theme=${JSON.stringify(theme)}`);
  check(await ev('(()=>{const b=document.querySelector(".workspace-launchers [data-action-key=action-apply]"),r=b.getBoundingClientRect();return b.textContent.includes("Apply for a New Card")&&r.top>=0&&r.bottom<innerHeight&&scrollY===0})()'),`${theme} ${width} card application immediately visible`);
  await click('.workspace-launchers [data-action-key=action-apply]');check(await ev('document.querySelector(".action-dialog").open&&document.querySelector(".card-account-summary").textContent.includes("0001")&&!document.querySelector(".card-application [name=account]")&&!document.querySelector(".card-application [name=customerId]")'),`${theme} ${width} application displays only server-selected owned account`);
  await click('[data-card-type=CREDIT]');check(await ev('document.querySelector(".card-application select[name=type]").value==="CREDIT"&&document.querySelector("[data-card-type=CREDIT]").getAttribute("aria-pressed")==="true"'),`${theme} ${width} visual card choice updates original field`);
  check(await ev('document.documentElement.scrollWidth<=innerWidth+1&&document.querySelector(".action-dialog").getBoundingClientRect().width<=innerWidth'),`${theme} ${width} card application fits viewport`);await shot(`card-application-${theme}-${width}`);await key('Escape','Escape',27);
 }
 await size(1440);await nav('/customer/cards#action-apply');
 await ev('(()=>{const s=document.querySelector(".card-application select[name=type]");s.add(new Option("Invalid test type","INVALID"));s.value="INVALID";s.form.requestSubmit();})()');await ready();check(await ev('document.querySelector(".action-dialog").open&&!!document.querySelector(".action-dialog .action-error")'),'invalid card type displays actual server validation in application');await shot('card-application-error');
 await click('[data-card-type=DEBIT]');await ev('document.querySelector(".card-application form").requestSubmit()');await ready();check(await ev('!!document.querySelector(".ui-toast")&&!document.querySelector(".action-dialog").open&&document.querySelector(".card-record-browser").textContent.includes("PENDING")'),'valid card application returns server success and pending card');await shot('card-application-pending');
 const debitId=await ev('[...document.querySelectorAll(".record")].map(r=>Object.fromEntries([...r.querySelectorAll("dl>div")].map(d=>[d.querySelector("dt").textContent.trim(),d.querySelector("dd").textContent.trim()]))).find(r=>r["card type"]==="DEBIT")["card id"]');
 await nav('/customer/cards#action-apply');await ev('document.querySelector(".card-application form").requestSubmit()');await ready();check(await ev('document.querySelector(".action-error").textContent.includes("already have an open card")'),'duplicate card request shows original business validation');
 const tampered=await ev(`(async()=>{const f=document.querySelector('.card-application form'),p=new URLSearchParams(new FormData(f));p.set('type','CREDIT');p.set('customerId','701');p.set('customer','701');p.set('account','920001');p.set('accountNumber','920001');p.set('dailyLimit','999999999');p.set('limit','999999999');const r=await fetch(f.getAttribute('action')||location.pathname,{method:'POST',body:p});return r.status;})()`);check(tampered===200,'tampered extra card fields cannot bypass authenticated application contract');await nav('/customer/cards');
 await identity(701,'CUSTOMER');await nav('/customer/cards');check(await ev('!document.querySelector(".card-record-browser")'),'other customer receives no card from tampered request');
 await identity(3,'CARD_SERVICES_OFFICER');await nav('/employee/dashboard#Cards');await ev(`const search=document.querySelector('#Cards .collection-toolbar input');search.value=${JSON.stringify(debitId)};search.dispatchEvent(new Event('input'))`);await ev(`document.querySelectorAll('#Cards tbody tr').forEach(r=>{if([...r.querySelectorAll('td small')].some(s=>s.textContent==='card id: '+${JSON.stringify(debitId)}))r.querySelector('.record-open').id='review-card-application'})`);await click('#review-card-application');await click(`.record-drawer [data-action-key="action-card-approve-${debitId}"]`);await ev('document.querySelector(".action-dialog textarea[name=reason]").value="Reviewed application in isolated browser test";document.querySelector(".action-dialog form").requestSubmit()');await ready();check(await ev('!!document.querySelector(".ui-toast")'),'Card Services officer processes application through original form');
 await cardLogin();await nav('/customer/cards');check(await ev('document.querySelector(".card-record-browser").textContent.includes("ACTIVE")&&document.querySelector(".card-record-browser").textContent.includes("PENDING")'),'customer sees actual approved debit and pending credit status');await shot('card-workspace-approved');
 check(errors.length===0,'zero uncaught JavaScript / console errors',errors);
 console.log(`UX BROWSER ${checks-failures.length}/${checks} PASSED`);
}catch(error){failures.push({page:current,error:String(error)});console.error(error);}
finally{fs.writeFileSync('verification/ux-browser-results.json',JSON.stringify({checks,passed:checks-failures.length,failures,consoleErrors:errors,sizes:[1440,1024,768,390]},null,2));ws.close();}
if(failures.length)process.exitCode=1;
